/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesRouteImport } from './routes/files'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as CirclesIndexRouteImport } from './routes/circles.index'
import { Route as CirclesCircleIdRouteImport } from './routes/circles.$circleId'
import { Route as MeetingMeetingIdRouteImport } from './routes/meeting.$meetingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIndexRoute = CirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesCircleIdRoute = CirclesCircleIdRouteImport.update({
  id: '/circles/$circleId',
  path: '/circles/$circleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingMeetingIdRoute = MeetingMeetingIdRouteImport.update({
  id: '/meeting/$meetingId',
  path: '/meeting/$meetingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/home': typeof HomeRoute
  '/meetings': typeof MeetingsRoute
  '/messages': typeof MessagesRoute
  '/saved': typeof SavedRoute
  '/circles/$circleId': typeof CirclesCircleIdRoute
  '/meeting/$meetingId': typeof MeetingMeetingIdRoute
  '/circles/': typeof CirclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/home': typeof HomeRoute
  '/meetings': typeof MeetingsRoute
  '/messages': typeof MessagesRoute
  '/saved': typeof SavedRoute
  '/circles/$circleId': typeof CirclesCircleIdRoute
  '/meeting/$meetingId': typeof MeetingMeetingIdRoute
  '/circles': typeof CirclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/home': typeof HomeRoute
  '/meetings': typeof MeetingsRoute
  '/messages': typeof MessagesRoute
  '/saved': typeof SavedRoute
  '/circles/$circleId': typeof CirclesCircleIdRoute
  '/meeting/$meetingId': typeof MeetingMeetingIdRoute
  '/circles/': typeof CirclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/home'
    | '/meetings'
    | '/messages'
    | '/saved'
    | '/circles/$circleId'
    | '/meeting/$meetingId'
    | '/circles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/home'
    | '/meetings'
    | '/messages'
    | '/saved'
    | '/circles/$circleId'
    | '/meeting/$meetingId'
    | '/circles'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/home'
    | '/meetings'
    | '/messages'
    | '/saved'
    | '/circles/$circleId'
    | '/meeting/$meetingId'
    | '/circles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRoute: typeof FilesRoute
  HomeRoute: typeof HomeRoute
  MeetingsRoute: typeof MeetingsRoute
  MessagesRoute: typeof MessagesRoute
  SavedRoute: typeof SavedRoute
  CirclesCircleIdRoute: typeof CirclesCircleIdRoute
  MeetingMeetingIdRoute: typeof MeetingMeetingIdRoute
  CirclesIndexRoute: typeof CirclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/': {
      id: '/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof CirclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/$circleId': {
      id: '/circles/$circleId'
      path: '/circles/$circleId'
      fullPath: '/circles/$circleId'
      preLoaderRoute: typeof CirclesCircleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$meetingId': {
      id: '/meeting/$meetingId'
      path: '/meeting/$meetingId'
      fullPath: '/meeting/$meetingId'
      preLoaderRoute: typeof MeetingMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRoute: FilesRoute,
  HomeRoute: HomeRoute,
  MeetingsRoute: MeetingsRoute,
  MessagesRoute: MessagesRoute,
  SavedRoute: SavedRoute,
  CirclesCircleIdRoute: CirclesCircleIdRoute,
  MeetingMeetingIdRoute: MeetingMeetingIdRoute,
  CirclesIndexRoute: CirclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
